version: '3.8'

services:
  cuenta-movimiento-service:
    build:
      context: .
      dockerfile: CuentaMovimientoDockerfile
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cuentamovimiento
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - database
      - rabbitmq

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: cuentamovimiento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"